config/routes.rb
Rails.application.routes.draw do
  #toppage________________________________________________________________________________________
  root to: "toppages#index"
  get "search", to:"toppages#search"
  
  #session________________________________________________________________________________________
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  
  #user___________________________________________________________________________________________
  resources :users, only: [:show, :edit, :update, :new, :create]
  
  #relationship_________________________________________________________________
  resources :relationships, only: [:create, :destroy]
  
  
  #group__________________________________________________________________________________________
  resources :groups, only: [:show, :edit, :update, :new, :create]
  
  #member_______________________________________________________________________
  resources :members, only: [:create, :destroy]
  
  #applicant____________________________________________________________________
  resources :applicants, only: [:create, :destroy]

  #grouprelationship____________________________________________________________
  resources :grouprelationships, only: [:create, :destroy]
  
  
  #company________________________________________________________________________________________
  resources :companies, only: [:show, :edit, :update, :new, :create]
  
  #companymember________________________________________________________________
  resources :companymembers, only: [:create, :destroy]
  
  #companyrelationship__________________________________________________________
  resources :companyrelationships, only: [:create, :destroy]
  
  #review_______________________________________________________________________
  resources :reviews, only: [:show, :new, :create, :destroy]


  #post___________________________________________________________________________________________
  resources :posts, only: [:show, :new, :create, :destroy] do
    member do
      get :favorite_users
    end
  end
  
  #favorite_____________________________________________________________________
  resources :favorites, only: [:create, :destroy]
  
  #comment______________________________________________________________________
  resources :comments, only: [:new, :create, :destroy]


  #event__________________________________________________________________________________________
  resources :events, only: [:show, :new, :create, :destroy] do
    member do
      get :clip_users
      get :join_users
    end
  end
  
  #clip_________________________________________________________________________
  resources :clips, only: [:create, :destroy]
  
  #join_________________________________________________________________________
  resources :joins, only: [:create, :destroy]
  
  #eventcomment_________________________________________________________________
  resources :eventcomments, only: [:new, :create, :destroy]

  
  resources :rooms

end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, presence: true, length: { maximum: 20 }
  validates :group_id, presence: true, length: {maximum: 20 },
                      format: { with: /[a-z0-9]/},
                      uniqueness: { case_sensitive: true }
  validates :profile, length: { maximum: 255 }
  
  mount_uploader :image, ImageUploader
  def icon
    if self.image.present?
      self.image
    else
      return "icon_group_default.jpg"
    end
  end
  
  #member_____________________________________________________________________________________________________
  has_many :members
  has_many :member_users, through: :members, source: :user
  
  #applicant____________________________________________________________________
  has_many :applicants
  has_many :applicant_users, through: :applicants, source: :user
  
  #grouprelationship____________________________________________________________
  has_many :grouprelationships
  has_many :group_followers, through: :grouprelationships, source: :user
  
  #post_______________________________________________________________________________________________________
  has_many :posts
  
  #event______________________________________________________________________________________________________
  has_many :events
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :require_user_logged_in, only: [:show, :edit, :update]
  
  def show
    @group = Group.find(params[:id])
    @member_users = @group.member_users.order("created_at DESC").page(params[:page])
    @applicant_users = @group.applicant_users.order("created_at DESC").page(params[:page])
    @group_followers = @group.group_followers.order("created_at DESC").page(params[:page])
    @posts = @group.posts("created_at DESC").page(params[:page])
    @events = @group.events("created_at DESC").page(params[:page])
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    
    if @group.update(group_params)
      redirect_to @group
    else
      flash.now[:danger] = "編集に失敗しました"
      render :edit
    end
  end

  def new
    @group = Group.new
    @groups = current_user.member_groups
  end

  def create
    @group = Group.new(group_params)
    @groups = current_user.member_groups.page(params[:page])
    
    if @group.save
      member = Member.new(user_id: current_user.id, group_id: @group.id, owner: true)
      member.save
    else
      flash.now[:danger] = "作成に失敗しました"
    end
  end
  
  private
  
  def group_params
    params.require(:group).permit(:name, :group_id, :profile, :image, :twitter, :facebook, :instagram, :otherlinka, :otherlinkb)
  end
end

app/views/groups/_groups.html.erb
<% if groups.count == 0 %>
  <p class="text-center">グループがありません</p>
<% end %>

<ul class="media-list">
  <% groups.each do |group| %>
    <li class="media well">
      <div class="media-left">
        <%= image_tag group.icon, size: 50, class: "media-object img-circle" %>
      </div>
      <div class="media-body">
        <div>
          <%= link_to group.name, group_path(group) %>
          <span class="text-muted">@<%= group.group_id %></span>
          <span class="text-muted pull-right"><%= group.member_users.count %>人が参加</span>
          <p class="panelprofile"><%= group.profile %></p>
        </div>
        <div class="flex-container">
          <div>
            <%= render "grouprelationships/follow_button", group: group %>
          </div>
          <div>
            <%= render "members/member_button", group: group %>
          </div>
        </div>
      </div>
    </li>
  <% end %>
</ul>

app/views/groups/_modal.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <%= form_for(@group, remote: true) do |f| %>
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title">グループを作成する</h4>
      </div>
      <div class="modal-body">
        <div class="field">
          <div class="form-group">
            <%= f.label :name, "グループ名" %>
            <%= f.text_field :name, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :group_id, "グループID" %>
            <%= f.text_field :group_id, class: "form-control" %>
          </div>
          <%= f.submit "作成", class: "btn btn-default btn-block" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/groups/_new.html.erb
<%= render 'modal' %>

app/views/groups/_save.js.erb
$(".timeline-groups").html("<%= escape_javascript(render 'groups/groups', groups: @groups) %>")
$("#divmodal").modal("hide")

app/views/groups/_tabs.html.erb
<div class="container">
  <div class="col-sm-2">
    <nav class="nav-sidebar user-sbar">
      <ul class="nav tabs text-center">

            <li class="active"><a href="#tab2" data-toggle="tab">投稿</a></li>
            <li class=""><a href="#tab3" data-toggle="tab">イベント</a></li>
            <li class=""><a href="#tab4" data-toggle="tab">ニュース</a></li>
            <li class=""><a href="#tab5" data-toggle="tab">メンバー</a></li>
            <% if current_user.member?(@group) %>
              <li class=""><a href="#tab5-1" data-toggle="tab">参加希望者</a></li>
            <% end %>
            <li class=""><a href="#tab6" data-toggle="tab">フォロワー</a></li>

      </ul>
    </nav>
  </div>


  <div class="tab-content">

    <div class="tab-pane active in fade timeline-posts" id="tab2">
      <%= render "posts/posts", posts: @posts %>
    </div>
    <div class="tab-pane fade timeline-events" id="tab3">
      <%= render "events/events", events: @events %>
    </div>
    <div class="tab-pane fade" id="tab4">
      準備中
    </div>
    <div class="tab-pane fade" id="tab5">
      <%= render "users/users", users: @member_users, imasen: "メンバーがいません" %>
    </div>
    <div class="tab-pane fade" id="tab5-1">
      <%= render "users/applicant_users", users: @applicant_users, imasen: "参加希望者はいません" %>
    </div>
    <div class="tab-pane fade" id="tab6">
      <%= render "users/users", users: @group_followers, imasen: "フォロワーがいません" %>
    </div>

  </div>
</div>

app/views/groups/create.js.erb
<%= render 'save' %>

app/views/groups/edit.html.erb
<h1 class="text-center">プロフィール編集</h1>

<div class="row col-xs-offset-2 col-xs-8">
  <div class="panel panel-default">
    <div class="panel-body">
      <%= form_for(@group, url: group_path(@group), html: { method: :patch }) do |f| %>
        <%= render "layouts/error_messages", model: f.object %>
        
        <div class="form-group">
          <%= f.label :image, "アイコン" %>
          <%= image_tag @group.icon, size: 120, class: "media-object img-circle img-responsive" %>
          <%= f.file_field :image %>
        </div>
        <div class="form-group">
          <%= f.label :name, "グループ名" %>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :profile, "プロフィール" %>
          <%= f.text_field :profile, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :twitter, "Twitter" %>
          <%= f.text_field :twitter, class: "form-control", placeholder: "例: https://twitter.com/connectexample" %>
        </div>
        <div class="form-group">
          <%= f.label :facebook, "facebook" %>
          <%= f.text_field :facebook, class: "form-control", placeholder: "例: https://www.facebook.com/connectexample" %>
        </div>
        <div class="form-group">
          <%= f.label :instagram, "Instagram" %>
          <%= f.text_field :instagram, class: "form-control", placeholder: "例: https://www.instagram.com/connectexample/" %>
        </div>
        <div class="form-group">
          <%= f.label :otherlinka, "その他リンク" %>
          <%= f.text_field :otherlinka, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :otherlinkb, "その他リンク2" %>
          <%= f.text_field :otherlinkb, class: "form-control" %>
        </div>
        
        <%= f.submit "編集を完了する", class: "btn btn-primary btn-block" %>
        
      <% end %>
    </div>
  </div>
</div>

app/views/groups/new.js.erb
$("#divmodal").html("<%= escape_javascript(render 'new') %>")
$("#divmodal").modal("show")

app/views/groups/show.html.erb
<div class="row user">
  <div class="user-left">
    <div class="user-icon">
      <%= image_tag @group.icon, size: 150, class: "img-circle" %>
    </div>
  </div>
  
  <div class="user-right">
    <div class="use">
      <span class="user-name"><%= @group.name %></span>
      <span class="user-id">@<%= @group.group_id %></span>
      <span class="pull-right flex-container">
        <%= render "applicants/applicant_button", group: @group %>
        <%= render "members/member_button", group: @group %>
        <%= render "grouprelationships/follow_button", group: @group, class: "follow-btn" %>
        <% if @member_users.include?(current_user) %>
          <%= link_to "プロフィールを編集", edit_group_path(@group), class: "edit-profile-btn" %>
        <% end %>
      </span>
    </div>
    <div class="user-prof">
      <%= @group.profile %>
    </div>
    <div class="user-link">
      <% if @group.twitter != "" %><%= link_to image_tag('sns/twitter.png', size: 20), @group.twitter %><% end %>
      <% if @group.facebook != "" %><%= link_to image_tag('sns/facebook.png', size: 20), @group.facebook %><% end %>
      <% if @group.instagram != "" %><%= link_to image_tag('sns/instagram.png', size: 20), @group.instagram %><% end %>
      <% if @group.otherlinka != "" %><%= link_to image_tag('sns/link.png', size: 20) + @group.otherlinka, @group.otherlinka %><% end %>
      <% if @group.otherlinkb != "" %><%= link_to image_tag('sns/link.png', size: 20) + @group.otherlinkb, @group.otherlinkb %><% end %>
    </div>
  </div>
  <div class="flex-container">
    <div class="counter-box">
      <div class="counter-text">
        メンバー
      </div>
      <div class="counter">
        <%= @group.member_users.count %>
      </div>
    </div>
    <div class="counter-box">
      <div class="counter-text">
        フォロワー
      </div>
      <div class="counter">
        <%= @group.group_followers.count %>
      </div>
    </div>
    <div class="counter-box">
      <div class="counter-text">
        投稿
      </div>
      <div class="counter">
        <%= @group.posts.count %>
      </div>
    </div>
    <div class="counter-box">
      <div class="counter-text">
        イベント
      </div>
      <div class="counter">
        <%= @group.events.count %>
      </div>
    </div>
  </div>
</div>

<div>
  <%= render "tabs" %>
</div>