config/routes.rb
Rails.application.routes.draw do
  #toppage________________________________________________________________________________________
  root to: "toppages#index"
  get "search", to:"toppages#search"
  
  #session________________________________________________________________________________________
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  
  #user___________________________________________________________________________________________
  resources :users, only: [:show, :edit, :update, :new, :create]
  
  #relationship_________________________________________________________________
  resources :relationships, only: [:create, :destroy]
  
  
  #group__________________________________________________________________________________________
  resources :groups, only: [:show, :edit, :update, :new, :create]
  
  #member_______________________________________________________________________
  resources :members, only: [:create, :destroy]
  
  #applicant____________________________________________________________________
  resources :applicants, only: [:create, :destroy]

  #grouprelationship____________________________________________________________
  resources :grouprelationships, only: [:create, :destroy]
  
  
  #company________________________________________________________________________________________
  resources :companies, only: [:show, :edit, :update, :new, :create]
  
  #companymember________________________________________________________________
  resources :companymembers, only: [:create, :destroy]
  
  #companyrelationship__________________________________________________________
  resources :companyrelationships, only: [:create, :destroy]
  
  #review_______________________________________________________________________
  resources :reviews, only: [:show, :new, :create, :destroy]


  #post___________________________________________________________________________________________
  resources :posts, only: [:show, :new, :create, :destroy] do
    member do
      get :favorite_users
    end
  end
  
  #favorite_____________________________________________________________________
  resources :favorites, only: [:create, :destroy]
  
  #comment______________________________________________________________________
  resources :comments, only: [:new, :create, :destroy]


  #event__________________________________________________________________________________________
  resources :events, only: [:show, :new, :create, :destroy] do
    member do
      get :clip_users
      get :join_users
    end
  end
  
  #clip_________________________________________________________________________
  resources :clips, only: [:create, :destroy]
  
  #join_________________________________________________________________________
  resources :joins, only: [:create, :destroy]
  
  #eventcomment_________________________________________________________________
  resources :eventcomments, only: [:new, :create, :destroy]

  
  resources :rooms

end

app/models/company.rb
class Company < ApplicationRecord
  validates :name, presence: true, length: { maximum: 20 },
                      uniqueness: { case_sensitive: true }
  validates :profile, length: { maximum: 255 }
  
  mount_uploader :image, ImageUploader
  def icon
    if self.image.present?
      self.image
    else
      return "icon_company_default.png"
    end
  end
  
  #companymember__________________________________________________________________________________
  has_many :companymembers
  has_many :member_users, through: :companymembers, source: :user
  
  #review_______________________________________________________________________
  has_many :reviews

  #companyrelationship__________________________________________________________
  has_many :companyrelationships
  has_many :company_followers, through: :companyrelationships, source: :user
  
  #post___________________________________________________________________________________________
  has_many :posts
  
  #event__________________________________________________________________________________________
  has_many :events
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :require_user_logged_in, only: [:show, :edit, :update]
  
  def show
    @company = Company.find(params[:id])
    @member_users = @company.member_users.order("created_at DESC").page(params[:page])
    @company_followers = @company.company_followers.order("created_at DESC").page(params[:page])
    @posts = @company.posts("created_at DESC").page(params[:page])
    @events = @company.events("created_at DESC").page(params[:page])
    @reviews = @company.reviews("created_at DESC").page(params[:page])
  end

  def edit
    @company = Company.find(params[:id])
  end

  def update
    @company = Company.find(params[:id])
    
    if @company.update(company_params)
      redirect_to @company
    else
      flash.now[:danger] = "編集に失敗しました"
      render :edit
    end
  end

  def new
    @company = Company.new
  end

  def create
    @company = Company.new(company_params)
      
    if @company.save
      companymember = Companymember.new(user_id: current_user.id, company_id: @company.id, owner: true)
      companymember.save
      redirect_to @company
    else
      flash[:danger] = "企業の登録に失敗しました。" 
      render :new
    end
  end
  
  private
  
  def company_params
    params.require(:company).permit(:name, :profile, :image, :twitter, :facebook, :officiallink)
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
  
  require "nokogiri"
  require "open-uri"
  
  def get_cmpn_news(word)
    
    url = URI.escape("https://news.google.com/gn/news/search/section/q/#{word}/#{word}/?hl=ja&gl=JP&ned=jp")
    
    charset = nil
    html = open(url) do |f|
      charset = f.charset
      f.read
    end
  
    doc = Nokogiri::HTML.parse(html, nil, charset)
  
    array = Array.new
    
  
    doc.xpath("//*[@class='PaqQNc']").each do |node|
  
      title = node.css(".nuEeue.hzdq5d.ME7ew").inner_text
      link = node.css(".nuEeue.hzdq5d.ME7ew").attribute("href").value


      begin
        img = node.css(".lmFAjc").attribute("src").value
      rescue
        img = ""
      end
      
      news_source = node.css(".IH8C7b.Pc0Wt").inner_text
      
      array << {title: title, link: link, img: img, news_source: news_source}
    end
    
    return array
    
  end
end

app/views/companies/_companies.html.erb
<% if companies.count == 0 %>
  <p class="text-center"><%= imasen %></p>
<% end %>

<ul class="media-list">
  <% companies.each do |company| %>
    <li class="media well">
      <div class="media-left">
        <%= image_tag company.icon, size: 50, class: "media-object img-circle" %>
      </div>
      <div class="media-body">
        <div>
          <%= link_to company.name, company %>
          <p class="panelprofile"><%= company.profile %></p>
        </div>
        <div>
          <%= render "companyrelationships/follow_button", company: company %>
        </div>
      </div>
    </li>
  <% end %>
  <%= paginate companies %>
</ul>

app/views/companies/_news.html.erb
<ul>
  <% array.each do |news| %>
    <li class="media well">
      <div class="media-left">
        <% if news[:img] == "" %>
          <%= image_tag "Noimage.jpg", size: 100, class: "media-object" %>
        <% else %>
          <%= image_tag news[:img], size: 100, class: "media-object" %>
        <% end %>
      </div>
      <div class="media-body">
        <%= link_to news[:title], news[:link] %>
        <p><%= news[:news_source] %></p>
      </div>
    </li>
  <% end %>
</ul>

app/views/companies/_tabs.html.erb
<div class="container">
  <div class="col-sm-2">
    <nav class="nav-sidebar user-sbar">
      <ul class="nav tabs text-center">
            <li class=""><a href="#tab1" data-toggle="tab">情報</a></li>
            <li class="active"><a href="#tab2" data-toggle="tab">投稿</a></li>
            <li class=""><a href="#tab3" data-toggle="tab">イベント</a></li>
            <li class=""><a href="#tab4" data-toggle="tab">ニュース</a></li>
            <li class=""><a href="#tab5" data-toggle="tab">口コミ</a></li>
            <li class=""><a href="#tab6" data-toggle="tab">メンバー</a></li>
            <li class=""><a href="#tab7" data-toggle="tab">フォロワー</a></li>
      </ul>
    </nav>
  </div>


  <div class="tab-content">
    <div class="tab-pane fade" id="tab1">
      準備中
    </div>
    <div class="tab-pane active in fade timeline-posts" id="tab2">
      <%= render "posts/posts", posts: @posts %>
    </div>
    <div class="tab-pane fade timeline-events" id="tab3">
      <%= render "events/events", events: @events %>
    </div>
    <div class="tab-pane fade" id="tab4">
      <%= render "news", array: get_cmpn_news(@company.name.delete!("株式会社")) %>
    </div>
    <div class="tab-pane fade" id="tab5">
      <h4>
          <span class="review_button pull-right">
            <%= link_to "口コミを投稿する", new_review_path, remote: true %>
          </span>
      </h4>
      <div class="timeline-reviews">
        <%= render "reviews/reviews", reviews: @reviews %>
      </div>
    </div>
    <div class="tab-pane fade" id="tab6">
      <%= render "users/users", users: @member_users, imasen: "メンバーがいません" %>
    </div>
    <div class="tab-pane fade" id="tab7">
      <%= render "users/users", users: @company_followers, imasen: "フォロワーがいません" %>
    </div>
  </div>
</div>

app/views/companies/edit.html.erb
<h1 class="text-center">プロフィール編集</h1>

<div class="row col-xs-offset-2 col-xs-8">
  <div class="panel panel-default">
    <div class="panel-body">
      <%= form_for(@company, url: company_path(@company), html: { method: :patch }) do |f| %>
        <%= render "layouts/error_messages", model: f.object %>
        
        <div class="form-group">
          <%= f.label :image, "アイコン" %>
          <%= image_tag @company.icon, size: 120, class: "media-object img-circle img-responsive" %>
          <%= f.file_field :image %>
        </div>
        <div class="form-group">
          <%= f.label :name, "グループ名" %>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :profile, "プロフィール" %>
          <%= f.text_field :profile, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :officiallink, "公式サイト" %>
          <%= f.text_field :officiallink, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :twitter, "Twitter" %>
          <%= f.text_field :twitter, class: "form-control", placeholder: "例: https://twitter.com/connectexample" %>
        </div>
        <div class="form-group">
          <%= f.label :facebook, "facebook" %>
          <%= f.text_field :facebook, class: "form-control", placeholder: "例: https://www.facebook.com/connectexample" %>
        </div>
        
        <%= f.submit "編集を完了する", class: "btn btn-primary btn-block" %>
        
      <% end %>
    </div>
  </div>
</div>

app/views/companies/new.html.erb
<div class="row login-panel">
    <div class="panel panel-default">
      <div class="panel-header">
        <h2 class="text-center">企業情報作成</h2>
      </div>
      <div class="panel-body">
        <%= form_for(@company) do |f| %>
          <%= render "layouts/error_messages", model: f.object %>
          <div class="form-group">
            <%= f.label :name, "名前" %>
            <%= f.text_field :name, class: "form-control" %>
          </div>
          
          <%= f.submit "新規登録", class: "btn btn-primary btn-block" %>
        <% end %>
      </div>
    </div>
  </div>

app/views/companies/show.html.erb
<div class="row user">
  <div class="user-left">
    <div class="user-icon">
      <%= image_tag @company.icon, size: 150, class: "img-circle" %>
    </div>
  </div>
  
  <div class="user-right">
    <div class="use">
      <span class="user-name"><%= @company.name %></span>
      <span class="pull-right flex-container">
        <%= render "companyrelationships/follow_button", company: @company, class: "follow-btn" %>
        <% if @member_users.include?(current_user) %>
          <%= link_to "プロフィールを編集", edit_company_path(@company), class: "edit-profile-btn" %>
        <% end %>
      </span>
    </div>
    <div class="user-prof">
      <%= @company.profile %>
    </div>
    <div class="user-link">
      <% if @company.twitter != "" %><%= link_to image_tag('sns/twitter.png', size: 20), @company.twitter %><% end %>
      <% if @company.facebook != "" %><%= link_to image_tag('sns/facebook.png', size: 20), @company.facebook %><% end %>
      <% if @company.officiallink != "" %><%= link_to image_tag('sns/link.png', size: 20) + @company.officiallink, @company.officiallink %><% end %>
    </div>
  </div>
  <div class="flex-container">
    <div class="counter-box">
      <div class="counter-text">
        フォロワー
      </div>
      <div class="counter">
        <%= @company.company_followers.count %>
      </div>
    </div>
    <div class="counter-box">
      <div class="counter-text">
        メンバー
      </div>
      <div class="counter">
        <%= @company.member_users.count %>
      </div>
    </div>
    <div class="counter-box">
      <div class="counter-text">
        投稿
      </div>
      <div class="counter">
        <%= @company.posts.count %>
      </div>
    </div>
    <div class="counter-box">
      <div class="counter-text">
        イベント
      </div>
      <div class="counter">
        <%= @company.events.count %>
      </div>
    </div>
    <div class="counter-box">
      <div class="counter-text">
        掲示板
      </div>
      <div class="counter">
        <%= @company.reviews.count %>
      </div>
    </div>
  </div>
</div>

<div>
  <%= render "tabs" %>
</div>