config/routes.rb
Rails.application.routes.draw do
  #toppage________________________________________________________________________________________
  root to: "toppages#index"
  get "search", to:"toppages#search"
  
  #session________________________________________________________________________________________
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  
  #user___________________________________________________________________________________________
  resources :users, only: [:show, :edit, :update, :new, :create]
  
  #relationship_________________________________________________________________
  resources :relationships, only: [:create, :destroy]
  
  
  #group__________________________________________________________________________________________
  resources :groups, only: [:show, :edit, :update, :new, :create]
  
  #member_______________________________________________________________________
  resources :members, only: [:create, :destroy]
  
  #applicant____________________________________________________________________
  resources :applicants, only: [:create, :destroy]

  #grouprelationship____________________________________________________________
  resources :grouprelationships, only: [:create, :destroy]
  
  
  #company________________________________________________________________________________________
  resources :companies, only: [:show, :edit, :update, :new, :create]
  
  #companymember________________________________________________________________
  resources :companymembers, only: [:create, :destroy]
  
  #companyrelationship__________________________________________________________
  resources :companyrelationships, only: [:create, :destroy]
  
  #review_______________________________________________________________________
  resources :reviews, only: [:show, :new, :create, :destroy]


  #post___________________________________________________________________________________________
  resources :posts, only: [:show, :new, :create, :destroy] do
    member do
      get :favorite_users
    end
  end
  
  #favorite_____________________________________________________________________
  resources :favorites, only: [:create, :destroy]
  
  #comment______________________________________________________________________
  resources :comments, only: [:new, :create, :destroy]


  #event__________________________________________________________________________________________
  resources :events, only: [:show, :new, :create, :destroy] do
    member do
      get :clip_users
      get :join_users
    end
  end
  
  #clip_________________________________________________________________________
  resources :clips, only: [:create, :destroy]
  
  #join_________________________________________________________________________
  resources :joins, only: [:create, :destroy]
  
  #eventcomment_________________________________________________________________
  resources :eventcomments, only: [:new, :create, :destroy]

  
  resources :rooms

end

app/models/eventcomment.rb
class Eventcomment < ApplicationRecord
  belongs_to :user
  belongs_to :event
  
  validates :user_id, presence: true
  validates :event_id, presence: true
  validates :content, length: { maximum: 500 }
end

app/controllers/eventcomments_controller.rb
class EventcommentsController < ApplicationController
  before_action :require_user_logged_in, only: [:new, :create, :destroy]

  def new
    @eventcomment = current_user.eventcomments.build
  end

  def create
    @event = Event.find_by(params[:id])
    @eventcomment = current_user.eventcomments.build(eventcomment_params)
    @eventcomment.event = @event
    @eventcomment.save
    @eventcomments = current_user.eventcomments.page(params[:page])
  end

  def destroy
    @eventcomment.destroy
    redirect_to "/"
  end
  
  private
  
  def eventcomment_params
    params.require(:eventcomment).permit(:content, :user_id, :event_id)
  end
end

app/views/eventcomments/_eventcomments.html.erb
<% if eventcomments.count == 0 %>
  <p class="text-center">コメントがありません</p>
<% end %>

<ul class="media-list">
    <% eventcomments.each do |comment| %>
      <% user = comment.user %>
      <li class="media well">
        <div class="media-left">
          <%= image_tag user.icon, size: 50, class: "media-object img-circle" %>
        </div>
        <div class="media-body">
          <%= link_to user.name, user_path(user) %>
          <span class="text-muted"><%= user.user_id %></span>
          <% if current_user == @user %>
            <span class="pull-right"><%= link_to image_tag("trash.png", size: 10), @eventcomment, method: :delete, data: { confirm: "削除しますか？" } %></span>
          <% end %>
          <p class="text-muted"><%= comment.created_at.strftime('%Y/%m/%d %H:%M') %></p>
          <p><%= comment.content %></p>
        </div>
      </li>
    <% end %>
</ul>

app/views/eventcomments/_modal.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <%= form_for(@eventcomment, remote: true) do |f| %>
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title">コメントする</h4>
      </div>
      <div class="modal-body">
        <div class="field">
          <div class="form-group">
            <%= f.text_area :content, class: "form-control", rows: 10 %>
          </div>
          <%= f.submit "投稿", class: "btn btn-default" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/eventcomments/_new.html.erb
<%= render 'modal' %>

app/views/eventcomments/_save.js.erb
$(".ecomments").html("<%= escape_javascript(render 'eventcomments/eventcomments', eventcomments: @eventcomments) %>")
$("#divmodal").modal("hide")

app/views/eventcomments/create.js.erb
<%= render 'save' %>

app/views/eventcomments/new.js.erb
$("#divmodal").html("<%= escape_javascript(render 'new') %>")
$("#divmodal").modal("show")